menu:
  首页:
    url: /
    icon: fas fa-home
  标签:
    url: /tags
    icon: fas fa-tags
  分类:
    url: /categories
    icon: fas fa-bookmark
  归档:
    url: /archives
    icon: fas fa-archive
  关于:
    url: /about
    icon: fas fa-user-circle
  友链:
    url: /friends
    icon: fas fa-address-book

favicon: /favicon.png
logo: /medias/logo.png

cover:
  showPrevNext: true
  showIndicators: true
  autoLoop: true
  duration: 120
  intervalTime: 5000
  useConfig: false

subtitle:
  enable: true
  loop: false
  showCursor: true
  startDelay: 300
  typeSpeed: 100
  backSpeed: 50
  sub:
    - 不积跬步,无以至千里
    - To climb steep hills requires slow pace at first.

dream:
  enable: false

indexbtn:
  enable: true
  name: Github
  icon: fab fa-github-alt
  url: https://github.com/buptxinghan

socialLink:
  github: https://github.com/buptxinghan
  email: 1419395226@qq.com
  qq: 1419395226
  rss: true

githubLink:
  enable: true
  url: https://github.com/buptxinghan
  title: Fork Me

banner:
  enable: true
  random: true

profile:
  avatar: /medias/avatar.jpg
  career: Software Engineer
  introduction: If you wish to succeed, you should use persistence as your good friend, experience as your reference, prudence as your brother and hope as your sentry.

myProjects:
  enable: false

mySkills:
  enable: true
  data:
    Java:
      background: 'linear-gradient(to right, #FF0066 0%, #FF00CC 100%)'
      percent: 85%
    JavaScript:
      background: 'linear-gradient(to right, #9900FF 0%, #CC66FF 100%)'
      percent: 80%
    HTML5:
      background: 'linear-gradient(to right, #2196F3 0%, #42A5F5 100%)'
      percent: 80%
    CSS:
      background: 'linear-gradient(to right, #00BCD4 0%, #80DEEA 100%)'
      percent: 70%
    SQL:
      background: 'linear-gradient(to right, #4CAF50 0%, #81C784 100%)'
      percent: 90%
    程序设计:
      background: 'linear-gradient(to right, #FFEB3B 0%, #FFF176 100%)'
      percent: 75%

myGallery:
  enable: true
  data:
    - /medias/featureimages/0.jpg
    - /medias/featureimages/1.jpg
    - /medias/featureimages/2.jpg

postInfo:
  date: true
  update: false
  wordCount: false
  totalCount: false
  min2read: false
  readCount: false

reward:
  enable: false

gitalk:
  enable: false

gitment:
  enable: false

disqus:
  enable: false

livere:
  enable: false

valine:
  enable: false

waline:
  enable: false

twikoo:
  enable: false
